loader_params:
    dataloader: "v2"
    train_bs: 2
    val_bs: 1
    csv_root: 'meta_files/meta_data.csv'
    scale_dose_dict: 'meta_files/PTV_DICT.json'
    pat_obj_dict: 'meta_files/Pat_Obj_DICT.json'
    num_workers: 8
    prefetch_factor : 2

    down_HU: -1000
    up_HU: 1000
    denom_norm_HU: 500

    in_size: [160, 160, 224]
    out_size: [160, 160, 224]

    dose_div_factor: 10 
    
    
model_params:
    model_name: 'mednext_d2'
    in_channels: 7
    out_channels: 1
    deep_supervision: False

lr: 0.0003
loss: l1
num_epochs: 500
act_sig: True
scale_out: 7.5

save_model_path: best_model.pth
save_pred_path: results